apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}-secret
type: Opaque
data:
  {{- with .Values.secret }}
  username: {{ .username | b64enc }}
  password: {{ .password | b64enc }}
  {{- end }}
